name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
       sudo apt update
       sudo apt install -y libgtest-dev
    - uses: actions/checkout@master
    - name: cmake
      run: cmake ./ -Dtest=ON
    - name: make
      run: make
    - name: tests
      run: make test
